[package]
name = "http_04"
version = "0.1.0"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]

[dependencies]
structopt = "0.2.10"
log = "0.4.3"
clap_flags = "0.2.0"

[build-dependencies]
structopt = "0.2.10"
clap_flags = "0.2.0"
